solution finally found
invariant_candidates found: 
type:  <class 'collections.deque'> , len:  17
INVARIANT CANDIDATE: ¬on(?x0, ?x1) [?x1: object, ?x0: object]
INVARIANT CANDIDATE: clear(?x0) ∨ ¬on(?x0, ?x0) [?x0: object]
INVARIANT CANDIDATE: ¬on(?x0, ?var0) ∨ clear(?x0) [?var0: object, ?x0: object]
INVARIANT CANDIDATE: ¬ontable(?x0) ∨ clear(?x0) [?x0: object]
INVARIANT CANDIDATE: clear(?x0) ∨ ¬on(?var0, ?x0) [?var0: object, ?x0: object]
INVARIANT CANDIDATE: holding(?x0) ∨ clear(?x0) [?x0: object]
INVARIANT CANDIDATE: ontable(?x0) ∨ ¬on(?var0, ?x0) [?var0: object, ?x0: object]
INVARIANT CANDIDATE: ontable(?x0) ∨ ¬on(?x0, ?var0) [?var0: object, ?x0: object]
INVARIANT CANDIDATE: ontable(?x0) ∨ holding(?x0) [?x0: object]
INVARIANT CANDIDATE: ontable(?x0) ∨ ¬clear(?x0) [?x0: object]
INVARIANT CANDIDATE: ontable(?x0) ∨ ¬on(?x0, ?x0) [?x0: object]
INVARIANT CANDIDATE: ¬on(?var0, ?var0) ∨ handempty() [?var0: object]
INVARIANT CANDIDATE: ¬holding(?x0) ∨ ¬clear(?x0) [?x0: object]
INVARIANT CANDIDATE: ¬holding(?x0) ∨ ¬on(?var0, ?x0) [?var0: object, ?x0: object]
INVARIANT CANDIDATE: ¬ontable(?x0) ∨ ¬holding(?x0) [?x0: object]
INVARIANT CANDIDATE: ¬holding(?x0) ∨ ¬on(?x0, ?x0) [?x0: object]
INVARIANT CANDIDATE: ¬holding(?x0) ∨ ¬on(?x0, ?var0) [?var0: object, ?x0: object]