fof(formula1, axiom,clear(c) | clear(d) | handempty(z) | holding(a) | ontable(b) | holding(d) | ontable(d) | ontable(a) | ontable(c) | holding(c) | on(d,c) | clear(b) | on(d,b)).
fof(formula2, axiom,clear(b) | clear(d) | holding(b) | holding(a) | ontable(d) | ontable(c) | handempty(z) | on(a,c) | holding(c) | clear(a) | on(a,b) | on(d,a) | on(c,d) | on(d,b) | clear(c)).
fof(formula3, axiom,ontable(a) | ontable(d) | handempty(z) | holding(a) | on(c,a) | holding(b) | on(a,b) | on(a,d) | clear(c) | clear(a) | holding(d) | clear(b) | on(c,d) | on(d,b) | holding(c) | on(b,c)).
fof(formula4, axiom,ontable(b) | ontable(d) | clear(c) | holding(a) | on(d,a) | ontable(a) | holding(c) | clear(d) | ontable(c) | on(a,c) | holding(b) | on(c,d) | handempty(z) | clear(a) | holding(d) | on(b,c)).
fof(formula5, axiom,handempty(z) | handempty(z) | clear(b) | ontable(a) | on(d,c) | handempty(z) | on(b,c) | clear(c) | clear(a) | ontable(d) | clear(d)).
fof(formula6, axiom,ontable(c) | ontable(d) | on(c,b) | holding(c) | handempty(z) | on(a,c) | holding(d) | on(d,a) | clear(d) | holding(a) | clear(a) | ontable(b) | clear(b) | clear(c)).
fof(formula7, axiom,clear(a) | clear(d) | holding(d) | holding(c) | handempty(z) | ontable(d) | on(c,d) | on(b,d) | holding(a) | ontable(c) | on(b,c) | clear(b) | holding(b) | clear(c)).
fof(formula8, axiom,ontable(d) | ontable(b) | holding(c) | on(b,c) | handempty(z) | holding(d) | clear(a) | on(a,b) | holding(b) | on(b,d) | ontable(c) | holding(a) | clear(c) | on(c,a) | on(c,b) | ontable(a) | on(a,c) | clear(b) | on(d,c)).
fof(formula9, axiom,clear(d) | clear(b) | on(a,c) | ontable(c) | handempty(z) | holding(a) | on(a,b) | on(b,c) | holding(c) | ontable(a) | on(b,d) | ontable(d) | on(b,a) | on(c,a) | clear(a) | on(d,a) | ontable(b) | clear(c)).
fof(formula0, negated_conjecture,